<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pais', 'doctrine');

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property float $x
 * @property float $y
 * @property Doctrine_Collection $Region
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method float               getX()      Returns the current record's "x" value
 * @method float               getY()      Returns the current record's "y" value
 * @method Doctrine_Collection getRegion() Returns the current record's "Region" collection
 * @method Pais                setId()     Sets the current record's "id" value
 * @method Pais                setNombre() Sets the current record's "nombre" value
 * @method Pais                setX()      Sets the current record's "x" value
 * @method Pais                setY()      Sets the current record's "y" value
 * @method Pais                setRegion() Sets the current record's "Region" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('x', 'float', 13, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 13,
             'scale' => '10',
             ));
        $this->hasColumn('y', 'float', 13, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 13,
             'scale' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Region', array(
             'local' => 'id',
             'foreign' => 'fk_pais'));
    }
}