<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tarea', 'doctrine');

/**
 * BaseTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $fecha_inicio
 * @property date $fecha_final
 * @property integer $periodisidad
 * @property integer $fk_id_planta
 * @property integer $fk_id_estado_tarea
 * @property integer $fk_id_tipo_tarea
 * @property EstadoTarea $EstadoTarea
 * @property Planta $Planta
 * @property Tipotarea $Tipotarea
 * 
 * @method integer     getId()                 Returns the current record's "id" value
 * @method date        getFechaInicio()        Returns the current record's "fecha_inicio" value
 * @method date        getFechaFinal()         Returns the current record's "fecha_final" value
 * @method integer     getPeriodisidad()       Returns the current record's "periodisidad" value
 * @method integer     getFkIdPlanta()         Returns the current record's "fk_id_planta" value
 * @method integer     getFkIdEstadoTarea()    Returns the current record's "fk_id_estado_tarea" value
 * @method integer     getFkIdTipoTarea()      Returns the current record's "fk_id_tipo_tarea" value
 * @method EstadoTarea getEstadoTarea()        Returns the current record's "EstadoTarea" value
 * @method Planta      getPlanta()             Returns the current record's "Planta" value
 * @method Tipotarea   getTipotarea()          Returns the current record's "Tipotarea" value
 * @method Tarea       setId()                 Sets the current record's "id" value
 * @method Tarea       setFechaInicio()        Sets the current record's "fecha_inicio" value
 * @method Tarea       setFechaFinal()         Sets the current record's "fecha_final" value
 * @method Tarea       setPeriodisidad()       Sets the current record's "periodisidad" value
 * @method Tarea       setFkIdPlanta()         Sets the current record's "fk_id_planta" value
 * @method Tarea       setFkIdEstadoTarea()    Sets the current record's "fk_id_estado_tarea" value
 * @method Tarea       setFkIdTipoTarea()      Sets the current record's "fk_id_tipo_tarea" value
 * @method Tarea       setEstadoTarea()        Sets the current record's "EstadoTarea" value
 * @method Tarea       setPlanta()             Sets the current record's "Planta" value
 * @method Tarea       setTipotarea()          Sets the current record's "Tipotarea" value
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_final', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('periodisidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_id_planta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_id_estado_tarea', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_id_tipo_tarea', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EstadoTarea', array(
             'local' => 'fk_id_estado_tarea',
             'foreign' => 'id'));

        $this->hasOne('Planta', array(
             'local' => 'fk_id_planta',
             'foreign' => 'id'));

        $this->hasOne('Tipotarea', array(
             'local' => 'fk_id_tipo_tarea',
             'foreign' => 'id'));
    }
}