<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estadotarea', 'doctrine');

/**
 * BaseEstadotarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Tarea
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getTarea()  Returns the current record's "Tarea" collection
 * @method Estadotarea         setId()     Sets the current record's "id" value
 * @method Estadotarea         setNombre() Sets the current record's "nombre" value
 * @method Estadotarea         setTarea()  Sets the current record's "Tarea" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadotarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estadotarea');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea', array(
             'local' => 'id',
             'foreign' => 'fk_id_estadotarea'));
    }
}