<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PotLuz', 'doctrine');

/**
 * BasePotLuz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $potencia
 * @property Doctrine_Collection $Luz
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method integer             getPotencia() Returns the current record's "potencia" value
 * @method Doctrine_Collection getLuz()      Returns the current record's "Luz" collection
 * @method PotLuz              setId()       Sets the current record's "id" value
 * @method PotLuz              setPotencia() Sets the current record's "potencia" value
 * @method PotLuz              setLuz()      Sets the current record's "Luz" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePotLuz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pot_luz');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('potencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Luz', array(
             'local' => 'id',
             'foreign' => 'fk_pot_luz'));
    }
}