<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Planta', 'doctrine');

/**
 * BasePlanta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $fk_usuario
 * @property integer $fk_semilla
 * @property date $fecha_nacimiento
 * @property string $madre
 * @property integer $esqueje
 * @property Semilla $Semilla
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Historial
 * @property Doctrine_Collection $Tarea
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method integer             getFkUsuario()        Returns the current record's "fk_usuario" value
 * @method integer             getFkSemilla()        Returns the current record's "fk_semilla" value
 * @method date                getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method string              getMadre()            Returns the current record's "madre" value
 * @method integer             getEsqueje()          Returns the current record's "esqueje" value
 * @method Semilla             getSemilla()          Returns the current record's "Semilla" value
 * @method Usuario             getUsuario()          Returns the current record's "Usuario" value
 * @method Doctrine_Collection getHistorial()        Returns the current record's "Historial" collection
 * @method Doctrine_Collection getTarea()            Returns the current record's "Tarea" collection
 * @method Planta              setId()               Sets the current record's "id" value
 * @method Planta              setNombre()           Sets the current record's "nombre" value
 * @method Planta              setFkUsuario()        Sets the current record's "fk_usuario" value
 * @method Planta              setFkSemilla()        Sets the current record's "fk_semilla" value
 * @method Planta              setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method Planta              setMadre()            Sets the current record's "madre" value
 * @method Planta              setEsqueje()          Sets the current record's "esqueje" value
 * @method Planta              setSemilla()          Sets the current record's "Semilla" value
 * @method Planta              setUsuario()          Sets the current record's "Usuario" value
 * @method Planta              setHistorial()        Sets the current record's "Historial" collection
 * @method Planta              setTarea()            Sets the current record's "Tarea" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fk_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_semilla', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('madre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('esqueje', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Semilla', array(
             'local' => 'fk_semilla',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'fk_usuario',
             'foreign' => 'id'));

        $this->hasMany('Historial', array(
             'local' => 'id',
             'foreign' => 'fk_planta'));

        $this->hasMany('Tarea', array(
             'local' => 'id',
             'foreign' => 'fk_id_planta'));
    }
}