<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Region', 'doctrine');

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property float $x
 * @property float $y
 * @property integer $fk_pais
 * @property Pais $Pais
 * @property Doctrine_Collection $Localidad
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method float               getX()         Returns the current record's "x" value
 * @method float               getY()         Returns the current record's "y" value
 * @method integer             getFkPais()    Returns the current record's "fk_pais" value
 * @method Pais                getPais()      Returns the current record's "Pais" value
 * @method Doctrine_Collection getLocalidad() Returns the current record's "Localidad" collection
 * @method Region              setId()        Sets the current record's "id" value
 * @method Region              setNombre()    Sets the current record's "nombre" value
 * @method Region              setX()         Sets the current record's "x" value
 * @method Region              setY()         Sets the current record's "y" value
 * @method Region              setFkPais()    Sets the current record's "fk_pais" value
 * @method Region              setPais()      Sets the current record's "Pais" value
 * @method Region              setLocalidad() Sets the current record's "Localidad" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('x', 'float', 13, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 13,
             'scale' => '10',
             ));
        $this->hasColumn('y', 'float', 13, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0000000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 13,
             'scale' => '10',
             ));
        $this->hasColumn('fk_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pais', array(
             'local' => 'fk_pais',
             'foreign' => 'id'));

        $this->hasMany('Localidad', array(
             'local' => 'id',
             'foreign' => 'fk_region'));
    }
}