<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Historial', 'doctrine');

/**
 * BaseHistorial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_planta
 * @property integer $litraje
 * @property decimal $temperatura
 * @property decimal $altura
 * @property integer $fk_tipo_cultivo
 * @property integer $hora_luz
 * @property integer $hora_oscuridad
 * @property decimal $humedad
 * @property decimal $ph
 * @property integer $fk_estado
 * @property integer $fk_etapa
 * @property integer $id
 * @property integer $fk_luz
 * @property date $fecha
 * @property Estado $Estado
 * @property Etapa $Etapa
 * @property Luz $Luz
 * @property Planta $Planta
 * @property TipoCultivo $TipoCultivo
 * 
 * @method integer     getFkPlanta()        Returns the current record's "fk_planta" value
 * @method integer     getLitraje()         Returns the current record's "litraje" value
 * @method decimal     getTemperatura()     Returns the current record's "temperatura" value
 * @method decimal     getAltura()          Returns the current record's "altura" value
 * @method integer     getFkTipoCultivo()   Returns the current record's "fk_tipo_cultivo" value
 * @method integer     getHoraLuz()         Returns the current record's "hora_luz" value
 * @method integer     getHoraOscuridad()   Returns the current record's "hora_oscuridad" value
 * @method decimal     getHumedad()         Returns the current record's "humedad" value
 * @method decimal     getPh()              Returns the current record's "ph" value
 * @method integer     getFkEstado()        Returns the current record's "fk_estado" value
 * @method integer     getFkEtapa()         Returns the current record's "fk_etapa" value
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getFkLuz()           Returns the current record's "fk_luz" value
 * @method date        getFecha()           Returns the current record's "fecha" value
 * @method Estado      getEstado()          Returns the current record's "Estado" value
 * @method Etapa       getEtapa()           Returns the current record's "Etapa" value
 * @method Luz         getLuz()             Returns the current record's "Luz" value
 * @method Planta      getPlanta()          Returns the current record's "Planta" value
 * @method TipoCultivo getTipoCultivo()     Returns the current record's "TipoCultivo" value
 * @method Historial   setFkPlanta()        Sets the current record's "fk_planta" value
 * @method Historial   setLitraje()         Sets the current record's "litraje" value
 * @method Historial   setTemperatura()     Sets the current record's "temperatura" value
 * @method Historial   setAltura()          Sets the current record's "altura" value
 * @method Historial   setFkTipoCultivo()   Sets the current record's "fk_tipo_cultivo" value
 * @method Historial   setHoraLuz()         Sets the current record's "hora_luz" value
 * @method Historial   setHoraOscuridad()   Sets the current record's "hora_oscuridad" value
 * @method Historial   setHumedad()         Sets the current record's "humedad" value
 * @method Historial   setPh()              Sets the current record's "ph" value
 * @method Historial   setFkEstado()        Sets the current record's "fk_estado" value
 * @method Historial   setFkEtapa()         Sets the current record's "fk_etapa" value
 * @method Historial   setId()              Sets the current record's "id" value
 * @method Historial   setFkLuz()           Sets the current record's "fk_luz" value
 * @method Historial   setFecha()           Sets the current record's "fecha" value
 * @method Historial   setEstado()          Sets the current record's "Estado" value
 * @method Historial   setEtapa()           Sets the current record's "Etapa" value
 * @method Historial   setLuz()             Sets the current record's "Luz" value
 * @method Historial   setPlanta()          Sets the current record's "Planta" value
 * @method Historial   setTipoCultivo()     Sets the current record's "TipoCultivo" value
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHistorial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('historial');
        $this->hasColumn('fk_planta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('litraje', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('temperatura', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('altura', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('fk_tipo_cultivo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hora_luz', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hora_oscuridad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('humedad', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('ph', 'decimal', 11, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             'scale' => '2',
             ));
        $this->hasColumn('fk_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_etapa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fk_luz', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'fk_estado',
             'foreign' => 'id'));

        $this->hasOne('Etapa', array(
             'local' => 'fk_etapa',
             'foreign' => 'id'));

        $this->hasOne('Luz', array(
             'local' => 'fk_luz',
             'foreign' => 'id'));

        $this->hasOne('Planta', array(
             'local' => 'fk_planta',
             'foreign' => 'id'));

        $this->hasOne('TipoCultivo', array(
             'local' => 'fk_tipo_cultivo',
             'foreign' => 'id'));
    }
}