<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Banco', 'doctrine');

/**
 * BaseBanco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_banco
 * @property Doctrine_Collection $Semilla
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombreBanco()  Returns the current record's "nombre_banco" value
 * @method Doctrine_Collection getSemilla()      Returns the current record's "Semilla" collection
 * @method Banco               setId()           Sets the current record's "id" value
 * @method Banco               setNombreBanco()  Sets the current record's "nombre_banco" value
 * @method Banco               setSemilla()      Sets the current record's "Semilla" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banco');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_banco', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Semilla', array(
             'local' => 'id',
             'foreign' => 'fk_banco'));
    }
}