<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Semilla', 'doctrine');

/**
 * BaseSemilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_semilla
 * @property integer $fk_banco
 * @property Banco $Banco
 * @property Doctrine_Collection $Planta
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getNombreSemilla()  Returns the current record's "nombre_semilla" value
 * @method integer             getFkBanco()        Returns the current record's "fk_banco" value
 * @method Banco               getBanco()          Returns the current record's "Banco" value
 * @method Doctrine_Collection getPlanta()         Returns the current record's "Planta" collection
 * @method Semilla             setId()             Sets the current record's "id" value
 * @method Semilla             setNombreSemilla()  Sets the current record's "nombre_semilla" value
 * @method Semilla             setFkBanco()        Sets the current record's "fk_banco" value
 * @method Semilla             setBanco()          Sets the current record's "Banco" value
 * @method Semilla             setPlanta()         Sets the current record's "Planta" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemilla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semilla');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_semilla', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('fk_banco', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Banco', array(
             'local' => 'fk_banco',
             'foreign' => 'id'));

        $this->hasMany('Planta', array(
             'local' => 'id',
             'foreign' => 'fk_semilla'));
    }
}