<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Luz', 'doctrine');

/**
 * BaseLuz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $fk_tipo_luz
 * @property integer $fk_pot_luz
 * @property integer $fk_usuario
 * @property PotLuz $PotLuz
 * @property TipoLuz $TipoLuz
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Historial
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getFkTipoLuz()   Returns the current record's "fk_tipo_luz" value
 * @method integer             getFkPotLuz()    Returns the current record's "fk_pot_luz" value
 * @method integer             getFkUsuario()   Returns the current record's "fk_usuario" value
 * @method PotLuz              getPotLuz()      Returns the current record's "PotLuz" value
 * @method TipoLuz             getTipoLuz()     Returns the current record's "TipoLuz" value
 * @method Usuario             getUsuario()     Returns the current record's "Usuario" value
 * @method Doctrine_Collection getHistorial()   Returns the current record's "Historial" collection
 * @method Luz                 setId()          Sets the current record's "id" value
 * @method Luz                 setFkTipoLuz()   Sets the current record's "fk_tipo_luz" value
 * @method Luz                 setFkPotLuz()    Sets the current record's "fk_pot_luz" value
 * @method Luz                 setFkUsuario()   Sets the current record's "fk_usuario" value
 * @method Luz                 setPotLuz()      Sets the current record's "PotLuz" value
 * @method Luz                 setTipoLuz()     Sets the current record's "TipoLuz" value
 * @method Luz                 setUsuario()     Sets the current record's "Usuario" value
 * @method Luz                 setHistorial()   Sets the current record's "Historial" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLuz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('luz');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fk_tipo_luz', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_pot_luz', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fk_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PotLuz', array(
             'local' => 'fk_pot_luz',
             'foreign' => 'id'));

        $this->hasOne('TipoLuz', array(
             'local' => 'fk_tipo_luz',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'fk_usuario',
             'foreign' => 'id'));

        $this->hasMany('Historial', array(
             'local' => 'id',
             'foreign' => 'fk_luz'));
    }
}