<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $apellido
 * @property string $nick
 * @property string $email
 * @property integer $fk_localidad
 * @property Localidad $Localidad
 * @property Doctrine_Collection $Luz
 * @property Doctrine_Collection $Planta
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getApellido()     Returns the current record's "apellido" value
 * @method string              getNick()         Returns the current record's "nick" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method integer             getFkLocalidad()  Returns the current record's "fk_localidad" value
 * @method Localidad           getLocalidad()    Returns the current record's "Localidad" value
 * @method Doctrine_Collection getLuz()          Returns the current record's "Luz" collection
 * @method Doctrine_Collection getPlanta()       Returns the current record's "Planta" collection
 * @method Usuario             setId()           Sets the current record's "id" value
 * @method Usuario             setNombre()       Sets the current record's "nombre" value
 * @method Usuario             setApellido()     Sets the current record's "apellido" value
 * @method Usuario             setNick()         Sets the current record's "nick" value
 * @method Usuario             setEmail()        Sets the current record's "email" value
 * @method Usuario             setFkLocalidad()  Sets the current record's "fk_localidad" value
 * @method Usuario             setLocalidad()    Sets the current record's "Localidad" value
 * @method Usuario             setLuz()          Sets the current record's "Luz" collection
 * @method Usuario             setPlanta()       Sets the current record's "Planta" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('apellido', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nick', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('fk_localidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Localidad', array(
             'local' => 'fk_localidad',
             'foreign' => 'id'));

        $this->hasMany('Luz', array(
             'local' => 'id',
             'foreign' => 'fk_usuario'));

        $this->hasMany('Planta', array(
             'local' => 'id',
             'foreign' => 'fk_usuario'));
    }
}