<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Etapa', 'doctrine');

/**
 * BaseEtapa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Historial
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getHistorial() Returns the current record's "Historial" collection
 * @method Etapa               setId()        Sets the current record's "id" value
 * @method Etapa               setNombre()    Sets the current record's "nombre" value
 * @method Etapa               setHistorial() Sets the current record's "Historial" collection
 * 
 * @package    pakal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEtapa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('etapa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Historial', array(
             'local' => 'id',
             'foreign' => 'fk_etapa'));
    }
}