<?php

/**
 * BancoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BancoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BancoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banco');
    }
}