<?php

/**
 * EstadoTareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoTareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoTareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoTarea');
    }
}