<?php

/**
 * HistorialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistorialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistorialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Historial');
    }
}