<?php

/**
 * LuzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LuzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LuzTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Luz');
    }
}