<?php

/**
 * PaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pais');
    }
}