<?php

/**
 * PlantaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Planta');
    }
}