<?php

/**
 * PotLuzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PotLuzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PotLuzTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PotLuz');
    }
}