<?php

/**
 * TipotareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipotareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipotareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipotarea');
    }
}