<?php

/**
 * TipoTareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTarea');
    }
}