<?php

/**
 * TipoLuzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoLuzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoLuzTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoLuz');
    }
}