<?php

/**
 * TipoCultivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoCultivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoCultivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCultivo');
    }
}