<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/15 17:25:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pakal',
  'username' => 'pakal',
  'password' => 'pakal1234',
  'name' => 'doctrine',
)),);
